# soft drinks
- name: Fanta
  price: 1.50
  event_price: 2.50
  currency: FANTA
  category: drink
- name: Ice Tea
  price: 1.50
  event_price: 2.50
  category: drink
  currency: ICETEA
- name: Ice Tea Zero
  price: 1.50
  event_price: 2.50
  category: drink
  currency: ICETEA_ZERO
- name: Cola
  price: 1.50
  event_price: 2.50
  currency: COKE
  category: drink
- name: Cola Zero
  price: 1.50
  event_price: 2.50
  currency: COKE_ZERO
  category: drink
- name: Schweppes
  price: 1.50
  event_price: 2.50
  currency: SCHWEPPES
  category: drink

# weird german stuff
- name: Fritz
  price: 2.00
  event_price: 3.00
  currency: FRITZ
  category: drink
- name: Fritz Zero
  price: 2.00
  event_price: 3.00
  currency: FRITZ_ZERO
  category: drink
- name: Club Mate
  price: 2.00
  event_price: 3.00
  currency: CM
  category: drink
- name: Club Mate Red
  price: 2.00
  event_price: 3.00
  currency: CMRED
  category: drink
- name: Club Mate Cola
  price: 2.00
  event_price: 3.00
  category: drink
  currency: CMCOLA
- name : Club Mate Winter
  price: 2.00
  event_price: 3.00
  category: drink
  currency: WINTER_MATE
- name: Flora Power
  price: 2.00
  event_price: 3.00
  category: drink
  currency: FLORA
- name : "Vitamalz"
  price: 2.00
  event_price: 3.00
  category: drink
  currency: VITAMALZ

# plain drinks
- name: Water (glass)
  price: 0.50
  event_price: 0.50
  currency: WATER_GLASS
  category: drink
- name: Water (bottle)
  price: 0.75
  event_price: 1.00
  currency: WATER
  category: drink
- name: Tea
  price: 0.50
  event_price: 0.75
  currency: TEA
  category: drink

# alcoholics
- name: Jupiler
  price: 1.50
  event_price: 2.50
  currency: JUPILER
  category: alcohol
- name: Duvel
  price: 2.50
  event_price: 3.50
  currency: DUVEL
  category: alcohol
- name: Chimay
  price: 4.00
  event_price: 6.00
  currency: CHIMAY
  category: alcohol

# snacks
- name: Other Snack
  price: 0.60
  event_price: 0.90
  currency: SNACK
  category: food
- name: Chips
  price: 0.60
  event_price: 0.90
  currency: CHIP
  category: food
- name: Snickers
  price: 0.60
  event_price: 0.90
  currency: SNICKERS
  category: food
- name: Twix
  price: 0.60
  event_price: 0.90
  currency: TWIX
  category: food
- name: Mars
  price: 0.60
  event_price: 0.90
  currency: MARS
  category: food
- name: "M&M"
  price: 0.60
  event_price: 0.90
  currency: MNM
  category: food
- name: KitKat
  price: 0.60
  event_price: 0.90
  category: food
  currency: KITKAT
- name: King Mints
  price: 0.60
  event_price: 0.90
  category: food
  currency: KING
- name: "1 Chupa Chups"
  price: 0.20
  event_price: 0.30
  currency: CHUPACHUPS
  category: food
- name: "Rolo"
  price: 0.60
  event_price: 0.90
  category: food
  currency: ROLO
- name: Popcorn
  price: 0.50
  event_price: 0.50
  currency: POPCORN
  category: food
- name: Bounty
  price: 0.60
  event_price: 0.90
  currency: BOUNTY
  category: food
- name: Lion
  price: 0.60
  event_price: 0.90
  currency: LION
  category: food

# frozen goods
- name: Ice Cream
  price: 1.00
  event_price: 1.50
  currency: ICE_CREAM
  category: food
- name: Pizza
  # Also listed as 3.50
  price: 2.00
  event_price: 3.50
  currency: PIZZA
  payback:
    account: Liabilities:Bar:Members:Bart
    amount: 1.63
  category: food

# apparel
- name: Wristband
  price: 1.00
  event_price: 1.50
  currency: WRISTBAND
  payback:
    account: Liabilities:Bar:Members:Marquis
    amount: 0.50
  category: swag
- name: T-Shirt
  price: 20.00
  event_price: 30.00
  currency: TSHIRT
  category: swag
- name: Hoodie
  price: 35.00
  event_price: 53.00
  currency: HOODIE
  category: swag

# unused products below

#- name: Soda
#  price: 1.50
#  event_price: 2.50
#  currency: SODA
#  category: drink
#- name: Club Mate Kraftstoff
#  currency: CMKRAFT
#  price: 2.00
#  event_price: 3.00
#  category: drink
#- name: SPRITE
#  price: 2.00
#  event_price: 3.00
#  currency: SPRITE
#  category: DRINK
#- name: "whole #!"
#  price: 20.00
#  event_price: 30.00
#  currency: WHOLENUM
#  category: misc
#- name: Cola Light
#  price: 2.50
#  event_price: 3.50
#  currency: COKE_LIGHT
#  category: drink
#- name: Cha-Cha
#  price: 0.50
#  event_price: 0.75
#  currency: CHACHA
#  category: food
#- name: Cider
#  price: 1.00
#  event_price: 1.50
#  currency: CIDER
#  category: alcohol
#- name: Joylent
#  price: 7.00
#  event_price: 10.00
#  currency: JOYLENT
#  payback:
#    account: Liabilities:Bar:Members:Bloemist
#    amount: 5.00
#- name: Curry
#  price: 5.00
#  event_price: 7.50
#  currency: CURRY
#  category: food
#- name: Kriek
#  price: 2.00
#  event_price: 3.00
#  currency: KRIEK
#  category: alcohol
#- name: Croque
#  price: 1.50
#  event_price: 2.25
#  currency: CROQUE
#  payback:
#    account: Liabilities:Bar:Members:Bloemist
#    amount: 1.00
#  category: food
#- name: Jenever
#  price: 2.00
#  event_price: 3.00
#  category: alcohol
#  payback:
#    account: Liabilities:Bar:Members:Bloemist
#    amount: 1.00
#  currency: JNVR
#- name: Leffe
#  price: 2.00
#  event_price: 3.00
#  category: alcohol
#  currency: LEFFE
#- name: Orval
#  price: 3.00
#  event_price: 4.50
#  category: alcohol
#  currency: ORVL
